spring:
  application:
    name: api-gateway

#  zipkin:
#    base-url: http://localhost:9411

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - content-type
              - Authorization
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowCredentials: true

      routes:
        - id: customers
          uri: lb://CUSTOMERS
          predicates:
            - Path=/api/customers/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/notification/**
        - id: authentification
          uri: lb://AUTHENTIFICATION
          predicates:
            - Path=/api/authentification/**
          filters:
            - AuthorizationFilter

server:
  port: 8083
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
