spring:
  application:
    name: api-gateway

#  zipkin:
#    base-url: http://localhost:9411
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http//172.16.1.36:80"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - PUT
              - POST
              - DELETE

      routes:
        - id: customers
          uri: lb://CUSTOMERS
          predicates:
            - Path=/api/customers/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/notification/**
        - id: authentification
          uri: lb://AUTHENTIFICATION
          predicates:
            - Path=/api/authentification/**
          filters:
            - AuthorizationFilter

server:
  port: 8083
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
