server:
  port: 8086
#  servlet:
#    context-path: /api/
spring:
  application:
    name: authentification
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/authentification
    username: postgres
    password: gernika54
#  zipkin:
#    base-url: http://localhost:9411
#  rabbitmq:
#    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: secret



